Onboarding refactor
yuumasato/have_you_heard pull request #74
Opened 2022-02-08 19:00 UTC by nilsonsasaki

Used pr #73 to lessen TextStyle uses

Removed circle page indicator from third page
updated Button on third page to an AppButton

Added a new forth page to redirect to "set user name"

Added const where it was possible

Now, you can navigate to "set user name" swiping left on third page or by the Button

(set user name will need an exit game popup to avoid returning to an empty screen)

2022-02-09 21:35 UTC, yuumasato requested changes
> Removed circle page indicator from third page

As we are continuing the swiping action, the page action should probably show 4 dots, instead of 3.

> updated Button on third page to an AppButton
The designers recommended the button be removed, :)

> (set user name will need an exit game popup to avoid returning to an empty screen)

Maybe the user should be allowed to swipe back and go back to the onboarding?
If that is not easy, it should be fine for the user to be "locked" in the "SetUserNameScreen".

2022-02-09 21:35 UTC, yuumasato commented on lib/ui/onboarding.dart
> +                )),
The CirclePageIndicator is being swiped together with the page, it is supposed to stay still.

2022-02-09 21:35 UTC, yuumasato commented on lib/ui/onboarding.dart
> +                          text: 'continue'.tr,
The "Continue" button can be removed.

2022-02-10 12:38 UTC, nilsonsasaki commented
moved back CiclePage indicator to a stack on top of page view 
added a forth dot to Circle Page Indicator
changed empty scaffold to a UserNameScreen (used set_user_name as a widget maybe cause performance issues)

removed AppButton

2022-02-11 23:44 UTC, yuumasato approved these changes

2022-02-11 23:44 UTC, merged